// Aagedal Media Converter
// Copyright 2025 Truls Aagedal
// SPDX-License-Identifier: GPL-3.0-or-later

import Foundation
import SwiftUI

/// Non-interactive SwiftUI view used by `MetadataExporter` to render a PDF
/// snapshot of a `VideoItem`'s metadata. The layout mirrors `ComparisonMetadataView`
/// but drops the chrome (comparison columns, loading indicators, links).
struct MetadataExportView: View {
    let item: VideoItem

    private var metadata: VideoMetadata? { item.metadata }

    var body: some View {
        VStack(alignment: .leading, spacing: 18) {
            header

            if let c2pa = item.c2paMetadata, c2pa.hasContentCredentials || c2pa.hasSignature {
                section(title: "Content Authenticity (C2PA)") {
                    c2paRows(c2pa)
                }
            }

            if let camera = item.cameraMetadata, camera.hasAnyData {
                section(title: "Camera") {
                    cameraRows(camera)
                }
            }

            section(title: "General") {
                generalRows
            }

            if let streams = metadata?.videoStreams, !streams.isEmpty {
                section(title: "Video") {
                    ForEach(streams.indices, id: \.self) { idx in
                        if streams.count > 1 {
                            streamHeader("Stream \(idx + 1)")
                        }
                        videoRows(streams[idx])
                    }
                }
            }

            if let streams = metadata?.audioStreams, !streams.isEmpty {
                section(title: "Audio") {
                    ForEach(streams.indices, id: \.self) { idx in
                        if streams.count > 1 {
                            streamHeader("Stream \(idx + 1)")
                        }
                        audioRows(streams[idx])
                    }
                }
            }

            if let streams = metadata?.subtitleStreams, !streams.isEmpty {
                section(title: "Subtitles") {
                    ForEach(streams.indices, id: \.self) { idx in
                        if streams.count > 1 {
                            streamHeader("Stream \(idx + 1)")
                        }
                        subtitleRows(streams[idx])
                    }
                }
            }

            footer
        }
        .foregroundStyle(.black)
    }

    // MARK: - Sections

    private var header: some View {
        VStack(alignment: .leading, spacing: 4) {
            Text("Metadata")
                .font(.title)
                .fontWeight(.semibold)
            Text(item.name)
                .font(.headline)
                .foregroundStyle(.gray)
            Text(item.url.path)
                .font(.caption)
                .foregroundStyle(.gray)
        }
        .padding(.bottom, 6)
    }

    private var footer: some View {
        VStack(alignment: .leading, spacing: 2) {
            Divider()
            Text("Generated by Aagedal Media Converter — \(Self.dateFormatter.string(from: Date()))")
                .font(.caption)
                .foregroundStyle(.gray)
        }
        .padding(.top, 12)
    }

    // MARK: - Content rows

    @ViewBuilder
    private var generalRows: some View {
        infoRow("Container", value: metadata?.containerLongName ?? metadata?.formatName)
        infoRow("Duration", value: item.duration)
        if let bytes = metadata?.sizeBytes ?? Optional(item.size) {
            infoRow("File Size", value: ByteCountFormatter.string(fromByteCount: bytes, countStyle: .file))
        }
        infoRow("Title", value: metadata?.title)
        infoRow("Artist", value: metadata?.artist)
        let creationDate: Date? = metadata?.containerCreationDate
            ?? (try? item.url.resourceValues(forKeys: [.creationDateKey]).creationDate)
        if let creationDate {
            infoRow("Date Created", value: Self.dateFormatter.string(from: creationDate))
        }
        let modificationDate: Date? = metadata?.containerModificationDate
            ?? (try? item.url.resourceValues(forKeys: [.contentModificationDateKey]).contentModificationDate)
        if let modificationDate {
            infoRow("Date Modified", value: Self.dateFormatter.string(from: modificationDate))
        }
        infoRow("Bit Rate", value: Self.formatBitRate(metadata?.bitRate))
        if let lat = metadata?.gpsLatitude, let lon = metadata?.gpsLongitude {
            infoRow("GPS", value: String(format: "%.6f, %.6f", lat, lon))
        }
        if let alt = metadata?.gpsAltitude {
            infoRow("GPS Altitude", value: String(format: "%.1f m", alt))
        }
        if let timecodes = metadata?.timecodes, !timecodes.isEmpty {
            if timecodes.count == 1 {
                infoRow("Timecode", value: timecodes[0].value)
            } else {
                ForEach(timecodes) { tc in
                    infoRow("Timecode (\(tc.source.label))", value: tc.value)
                }
            }
        } else {
            infoRow("Timecode", value: metadata?.timecode)
        }
        if let comment = item.metadataComment {
            infoRow("Comment", value: comment)
        }
        if let warnings = metadata?.warnings, !warnings.isEmpty {
            ForEach(warnings.indices, id: \.self) { idx in
                infoRow("Warning", value: warnings[idx])
            }
        }
    }

    @ViewBuilder
    private func videoRows(_ stream: VideoMetadata.VideoStream) -> some View {
        infoRow("Codec", value: stream.codecLongName ?? stream.codec)
        infoRow("Profile", value: stream.profile)
        infoRow("Track Title", value: stream.title)
        if let w = stream.width, let h = stream.height {
            infoRow("Resolution", value: "\(w) × \(h)")
        }
        infoRow("Display Aspect", value: stream.displayAspectRatio?.stringValue)
        infoRow("Pixel Aspect", value: stream.pixelAspectRatio?.stringValue)
        if let fr = stream.frameRate {
            infoRow("Frame Rate", value: fr.value.map { String(format: "%.3f fps", $0) } ?? fr.stringValue)
        }
        infoRow("Bit Depth", value: stream.bitDepth.map { "\($0)-bit" })
        infoRow("Bit Rate", value: Self.formatBitRate(stream.bitRate))
        infoRow("Chroma Subsampling", value: stream.chromaSubsampling)
        infoRow("Pixel Format", value: stream.pixelFormat)
        infoRow("Alpha Channel", value: stream.hasAlpha ? "Yes" : "No")
        infoRow("Color Primaries", value: stream.colorPrimaries)
        infoRow("Color Transfer", value: stream.colorTransfer)
        infoRow("Color Space", value: stream.colorSpace)
        infoRow("Color Range", value: stream.colorRange)
        infoRow("Chroma Location", value: stream.chromaLocation)
        if let interlaced = stream.isInterlaced {
            infoRow("Scan Type", value: interlaced ? "Interlaced" : "Progressive")
        } else {
            infoRow("Scan Type", value: stream.fieldOrder)
        }
        infoRow("Field Order", value: Self.formattedFieldOrder(stream))
        if stream.isDefault { infoRow("Default", value: "Yes") }
        if stream.isForced { infoRow("Forced", value: "Yes") }
    }

    @ViewBuilder
    private func audioRows(_ stream: VideoMetadata.AudioStream) -> some View {
        infoRow("Codec", value: stream.codecLongName ?? stream.codec)
        infoRow("Language", value: stream.languageCode?.uppercased())
        infoRow("Profile", value: stream.profile)
        infoRow("Sample Rate", value: stream.sampleRate.map { "\($0) Hz" })
        infoRow("Channels", value: stream.channels.map(String.init))
        infoRow("Channel Layout", value: stream.channelLayout)
        infoRow("Bit Depth", value: stream.bitDepth.map { "\($0)-bit" })
        infoRow("Bit Rate", value: Self.formatBitRate(stream.bitRate))
    }

    @ViewBuilder
    private func subtitleRows(_ stream: VideoMetadata.SubtitleStream) -> some View {
        infoRow("Codec", value: stream.codecLongName ?? stream.codec)
        infoRow("Language", value: stream.languageCode?.uppercased())
        infoRow("Title", value: stream.title)
        if stream.isDefault { infoRow("Default", value: "Yes") }
        if stream.isForced { infoRow("Forced", value: "Yes") }
        if stream.isHearingImpaired { infoRow("Hearing Impaired (SDH)", value: "Yes") }
    }

    @ViewBuilder
    private func cameraRows(_ camera: CameraMetadata) -> some View {
        infoRow("Manufacturer", value: camera.deviceManufacturer)
        infoRow("Model", value: camera.deviceModelName)
        infoRow("Serial Number", value: camera.deviceSerialNumber)
        infoRow("Lens", value: camera.lensModelName)
        infoRow("Time Zone", value: camera.timeZone)
        infoRow("Gamma/Color Profile", value: camera.captureGammaEquation)
        infoRow("Recording Mode", value: camera.recordingModeType)
        infoRow("Capture FPS", value: camera.captureFps)
        if let clipDate = camera.creationDate {
            infoRow("Clip Creation", value: Self.dateFormatter.string(from: clipDate))
        }
        if let entries = camera.userDescriptiveMetadata, !entries.isEmpty {
            ForEach(entries.indices, id: \.self) { idx in
                let entry = entries[idx]
                infoRow(entry.name.isEmpty ? "User Metadata" : entry.name, value: entry.content)
            }
        }
    }

    @ViewBuilder
    private func c2paRows(_ c2pa: C2PAMetadata) -> some View {
        if c2pa.hasSignature {
            infoRow("Signature", value: "Present")
        }
        infoRow("Claim Generator Info Name", value: c2pa.claimGeneratorInfoName)
        infoRow("Claim Generator", value: c2pa.claimGenerator)
        infoRow("Actions Action", value: c2pa.actionsAction)
        infoRow("Actions Digital Source Type", value: c2pa.actionsDigitalSourceType)
        infoRow("Manifest Store", value: c2pa.manifestStore)
        if let assertions = c2pa.assertions, !assertions.isEmpty {
            infoRow("Assertions", value: assertions.joined(separator: ", "))
        }
    }

    // MARK: - Primitives

    @ViewBuilder
    private func section<Content: View>(title: String, @ViewBuilder content: () -> Content) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            Text(title.uppercased())
                .font(.headline)
                .fontWeight(.bold)
                .padding(.bottom, 2)
            content()
            Divider()
        }
        .frame(maxWidth: .infinity, alignment: .leading)
    }

    private func streamHeader(_ title: String) -> some View {
        Text(title)
            .font(.subheadline)
            .fontWeight(.semibold)
            .foregroundStyle(.gray)
            .padding(.top, 6)
    }

    @ViewBuilder
    private func infoRow(_ title: String, value: String?) -> some View {
        if let value, !value.isEmpty {
            HStack(alignment: .firstTextBaseline, spacing: 12) {
                Text(title)
                    .font(.subheadline)
                    .fontWeight(.semibold)
                    .frame(minWidth: 140, alignment: .leading)
                Text(value)
                    .font(.system(.subheadline, design: .monospaced))
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .fixedSize(horizontal: false, vertical: true)
            }
        }
    }

    // MARK: - Helpers

    private static func formattedFieldOrder(_ stream: VideoMetadata.VideoStream) -> String? {
        guard let order = stream.fieldOrder else { return nil }
        switch order {
        case "tt": return "Top Field First (TFF)"
        case "bb": return "Bottom Field First (BFF)"
        case "progressive", "unknown": return nil
        default: return order
        }
    }

    private static func formatBitRate(_ value: Int64?) -> String? {
        guard let value, value > 0 else { return nil }
        if value >= 1_000_000 {
            return String(format: "%.2f Mbps", Double(value) / 1_000_000)
        } else if value >= 1_000 {
            return String(format: "%.1f kbps", Double(value) / 1_000)
        }
        return "\(value) bps"
    }

    private static let dateFormatter: DateFormatter = {
        let f = DateFormatter()
        f.dateStyle = .medium
        f.timeStyle = .medium
        return f
    }()
}
