// Aagedal Media Converter
// Copyright 2025 Truls Aagedal
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

import Foundation
import OSLog

/// Generates metadata sidecar files for image sequence exports, preserving
/// source color space and technical specifications that image formats cannot embed.
struct MetadataSidecarGenerator {

    private static let logger = Logger(subsystem: "com.aagedal.MediaConverter", category: "MetadataSidecarGenerator")

    enum SidecarFormat: String, CaseIterable, Identifiable, Sendable {
        case markdown = "Markdown"
        case json = "JSON"

        var id: String { rawValue }

        var fileExtension: String {
            switch self {
            case .markdown: return "md"
            case .json: return "json"
            }
        }
    }

    /// Generates a metadata sidecar file in the specified output folder.
    /// Errors are logged but do not propagate — sidecar generation should never fail a conversion.
    static func generateSidecar(
        originalFileName: String,
        outputFolder: URL,
        metadata: VideoMetadata,
        cameraMetadata: CameraMetadata?,
        format: SidecarFormat
    ) {
        let sidecarFileName = "SourceMetadata_\(originalFileName).\(format.fileExtension)"
        let sidecarURL = outputFolder.appendingPathComponent(sidecarFileName)

        let content: String
        switch format {
        case .markdown:
            content = generateMarkdown(originalFileName: originalFileName, metadata: metadata, cameraMetadata: cameraMetadata)
        case .json:
            content = generateJSON(originalFileName: originalFileName, metadata: metadata, cameraMetadata: cameraMetadata)
        }

        do {
            try content.write(to: sidecarURL, atomically: true, encoding: .utf8)
            logger.info("Metadata sidecar written: \(sidecarFileName)")
        } catch {
            logger.error("Failed to write metadata sidecar: \(error.localizedDescription)")
        }
    }

    // MARK: - Markdown Generation

    private static func generateMarkdown(originalFileName: String, metadata: VideoMetadata, cameraMetadata: CameraMetadata?) -> String {
        var lines: [String] = []
        lines.append("# Source Metadata: \(originalFileName)")
        lines.append("")

        // Color Space section (primary focus)
        if let video = metadata.primaryVideoStream {
            let colorRows = colorSpaceRows(from: video)
            if !colorRows.isEmpty {
                lines.append("## Color Space")
                lines.append("")
                lines.append(markdownTable(colorRows))
                lines.append("")
            }
        }

        // Video section
        if let video = metadata.primaryVideoStream {
            let videoRows = videoRows(from: video)
            if !videoRows.isEmpty {
                lines.append("## Video")
                lines.append("")
                lines.append(markdownTable(videoRows))
                lines.append("")
            }
        }

        // Audio section(s)
        for (index, audio) in metadata.audioStreams.enumerated() {
            let audioRows = audioRows(from: audio)
            if !audioRows.isEmpty {
                let streamLabel = metadata.audioStreams.count > 1 ? " (Stream \(index + 1))" : ""
                lines.append("## Audio\(streamLabel)")
                lines.append("")
                lines.append(markdownTable(audioRows))
                lines.append("")
            }
        }

        // Container section
        let containerRows = containerRows(from: metadata)
        if !containerRows.isEmpty {
            lines.append("## Container")
            lines.append("")
            lines.append(markdownTable(containerRows))
            lines.append("")
        }

        // Camera section
        if let camera = cameraMetadata, camera.hasAnyData {
            let cameraRows = cameraRows(from: camera)
            if !cameraRows.isEmpty {
                lines.append("## Camera")
                lines.append("")
                lines.append(markdownTable(cameraRows))
                lines.append("")
            }
        }

        lines.append("---")
        lines.append("*Generated by Aagedal Media Converter*")
        lines.append("")

        return lines.joined(separator: "\n")
    }

    private static func markdownTable(_ rows: [(String, String)]) -> String {
        var lines: [String] = []
        lines.append("| Property | Value |")
        lines.append("|---|---|")
        for (property, value) in rows {
            lines.append("| \(property) | \(value) |")
        }
        return lines.joined(separator: "\n")
    }

    // MARK: - JSON Generation

    private static func generateJSON(originalFileName: String, metadata: VideoMetadata, cameraMetadata: CameraMetadata?) -> String {
        var root: [String: Any] = [:]
        root["sourceFile"] = originalFileName
        root["generatedBy"] = "Aagedal Media Converter"

        let formatter = ISO8601DateFormatter()
        root["generatedAt"] = formatter.string(from: Date())

        if let video = metadata.primaryVideoStream {
            let colorDict = colorSpaceDict(from: video)
            if !colorDict.isEmpty {
                root["colorSpace"] = colorDict
            }

            let videoDict = videoDict(from: video)
            if !videoDict.isEmpty {
                root["video"] = videoDict
            }
        }

        if !metadata.audioStreams.isEmpty {
            let audioArray = metadata.audioStreams.map { audioDict(from: $0) }
            root["audio"] = audioArray
        }

        let container = containerDict(from: metadata)
        if !container.isEmpty {
            root["container"] = container
        }

        if let camera = cameraMetadata, camera.hasAnyData {
            let cameraDict = cameraDict(from: camera)
            if !cameraDict.isEmpty {
                root["camera"] = cameraDict
            }
        }

        guard let data = try? JSONSerialization.data(withJSONObject: root, options: [.prettyPrinted, .sortedKeys]),
              let jsonString = String(data: data, encoding: .utf8) else {
            return "{}"
        }
        return jsonString + "\n"
    }

    // MARK: - Row/Dict Builders

    private static func colorSpaceRows(from video: VideoMetadata.VideoStream) -> [(String, String)] {
        var rows: [(String, String)] = []
        if let v = video.colorPrimaries { rows.append(("Color Primaries", v)) }
        if let v = video.colorTransfer { rows.append(("Color Transfer", v)) }
        if let v = video.colorSpace { rows.append(("Color Space", v)) }
        if let v = video.colorRange { rows.append(("Color Range", v)) }
        if let v = video.chromaSubsampling { rows.append(("Chroma Subsampling", v)) }
        if let v = video.chromaLocation { rows.append(("Chroma Location", v)) }
        if let v = video.bitDepth { rows.append(("Bit Depth", "\(v)")) }
        if let v = video.pixelFormat { rows.append(("Pixel Format", v)) }
        return rows
    }

    private static func colorSpaceDict(from video: VideoMetadata.VideoStream) -> [String: Any] {
        var dict: [String: Any] = [:]
        if let v = video.colorPrimaries { dict["colorPrimaries"] = v }
        if let v = video.colorTransfer { dict["colorTransfer"] = v }
        if let v = video.colorSpace { dict["colorSpace"] = v }
        if let v = video.colorRange { dict["colorRange"] = v }
        if let v = video.chromaSubsampling { dict["chromaSubsampling"] = v }
        if let v = video.chromaLocation { dict["chromaLocation"] = v }
        if let v = video.bitDepth { dict["bitDepth"] = v }
        if let v = video.pixelFormat { dict["pixelFormat"] = v }
        return dict
    }

    private static func videoRows(from video: VideoMetadata.VideoStream) -> [(String, String)] {
        var rows: [(String, String)] = []
        if let v = video.codec {
            let longName = video.codecLongName.map { " (\($0))" } ?? ""
            rows.append(("Codec", "\(v)\(longName)"))
        }
        if let v = video.profile { rows.append(("Profile", v)) }
        if let w = video.width, let h = video.height {
            rows.append(("Resolution", "\(w)\u{00D7}\(h)"))
        }
        if let v = video.frameRate { rows.append(("Frame Rate", v.stringValue)) }
        if let v = video.pixelAspectRatio { rows.append(("Pixel Aspect Ratio", v.stringValue)) }
        if let v = video.displayAspectRatio { rows.append(("Display Aspect Ratio", v.stringValue)) }
        if let v = video.fieldOrder { rows.append(("Field Order", v)) }
        if let v = video.isInterlaced { rows.append(("Interlaced", v ? "Yes" : "No")) }
        rows.append(("Alpha Channel", video.hasAlpha ? "Yes" : "No"))
        return rows
    }

    private static func videoDict(from video: VideoMetadata.VideoStream) -> [String: Any] {
        var dict: [String: Any] = [:]
        if let v = video.codec { dict["codec"] = v }
        if let v = video.codecLongName { dict["codecLongName"] = v }
        if let v = video.profile { dict["profile"] = v }
        if let v = video.width { dict["width"] = v }
        if let v = video.height { dict["height"] = v }
        if let v = video.frameRate { dict["frameRate"] = v.stringValue }
        if let v = video.pixelAspectRatio { dict["pixelAspectRatio"] = v.stringValue }
        if let v = video.displayAspectRatio { dict["displayAspectRatio"] = v.stringValue }
        if let v = video.fieldOrder { dict["fieldOrder"] = v }
        if let v = video.isInterlaced { dict["isInterlaced"] = v }
        dict["hasAlpha"] = video.hasAlpha
        return dict
    }

    private static func audioRows(from audio: VideoMetadata.AudioStream) -> [(String, String)] {
        var rows: [(String, String)] = []
        if let v = audio.codec {
            let longName = audio.codecLongName.map { " (\($0))" } ?? ""
            rows.append(("Codec", "\(v)\(longName)"))
        }
        if let v = audio.profile { rows.append(("Profile", v)) }
        if let v = audio.sampleRate { rows.append(("Sample Rate", "\(v) Hz")) }
        if let v = audio.channels { rows.append(("Channels", "\(v)")) }
        if let v = audio.channelLayout { rows.append(("Channel Layout", v)) }
        if let v = audio.bitDepth { rows.append(("Bit Depth", "\(v)")) }
        if let v = audio.bitRate { rows.append(("Bit Rate", "\(v)")) }
        if let v = audio.languageCode { rows.append(("Language", v)) }
        if let v = audio.title { rows.append(("Title", v)) }
        return rows
    }

    private static func audioDict(from audio: VideoMetadata.AudioStream) -> [String: Any] {
        var dict: [String: Any] = [:]
        if let v = audio.codec { dict["codec"] = v }
        if let v = audio.codecLongName { dict["codecLongName"] = v }
        if let v = audio.profile { dict["profile"] = v }
        if let v = audio.sampleRate { dict["sampleRate"] = v }
        if let v = audio.channels { dict["channels"] = v }
        if let v = audio.channelLayout { dict["channelLayout"] = v }
        if let v = audio.bitDepth { dict["bitDepth"] = v }
        if let v = audio.bitRate { dict["bitRate"] = v }
        if let v = audio.languageCode { dict["language"] = v }
        if let v = audio.title { dict["title"] = v }
        return dict
    }

    private static func containerRows(from metadata: VideoMetadata) -> [(String, String)] {
        var rows: [(String, String)] = []
        if let v = metadata.formatName {
            let longName = metadata.containerLongName.map { " (\($0))" } ?? ""
            rows.append(("Format", "\(v)\(longName)"))
        }
        if let v = metadata.duration { rows.append(("Duration", String(format: "%.3f s", v))) }
        if let v = metadata.bitRate { rows.append(("Bit Rate", "\(v)")) }
        if let v = metadata.sizeBytes { rows.append(("File Size", ByteCountFormatter.string(fromByteCount: v, countStyle: .file))) }
        if let v = metadata.timecode { rows.append(("Timecode", v)) }
        if let v = metadata.frameCount { rows.append(("Frame Count", "\(v)")) }
        if let v = metadata.comment { rows.append(("Comment", v)) }
        return rows
    }

    private static func containerDict(from metadata: VideoMetadata) -> [String: Any] {
        var dict: [String: Any] = [:]
        if let v = metadata.formatName { dict["format"] = v }
        if let v = metadata.containerLongName { dict["formatLongName"] = v }
        if let v = metadata.duration { dict["duration"] = v }
        if let v = metadata.bitRate { dict["bitRate"] = v }
        if let v = metadata.sizeBytes { dict["sizeBytes"] = v }
        if let v = metadata.timecode { dict["timecode"] = v }
        if let v = metadata.frameCount { dict["frameCount"] = v }
        if let v = metadata.comment { dict["comment"] = v }
        return dict
    }

    private static func cameraRows(from camera: CameraMetadata) -> [(String, String)] {
        var rows: [(String, String)] = []
        if let v = camera.deviceManufacturer { rows.append(("Manufacturer", v)) }
        if let v = camera.deviceModelName { rows.append(("Model", v)) }
        if let v = camera.deviceSerialNumber { rows.append(("Serial Number", v)) }
        if let v = camera.lensModelName { rows.append(("Lens", v)) }
        if let v = camera.captureGammaEquation { rows.append(("Gamma Equation", v)) }
        if let v = camera.recordingModeType { rows.append(("Recording Mode", v)) }
        if let v = camera.captureFps { rows.append(("Capture FPS", v)) }
        if let v = camera.timeZone { rows.append(("Time Zone", v)) }
        return rows
    }

    private static func cameraDict(from camera: CameraMetadata) -> [String: Any] {
        var dict: [String: Any] = [:]
        if let v = camera.deviceManufacturer { dict["manufacturer"] = v }
        if let v = camera.deviceModelName { dict["model"] = v }
        if let v = camera.deviceSerialNumber { dict["serialNumber"] = v }
        if let v = camera.lensModelName { dict["lens"] = v }
        if let v = camera.captureGammaEquation { dict["gammaEquation"] = v }
        if let v = camera.recordingModeType { dict["recordingMode"] = v }
        if let v = camera.captureFps { dict["captureFps"] = v }
        if let v = camera.timeZone { dict["timeZone"] = v }
        return dict
    }
}
