// Aagedal Media Converter
// Copyright © 2025 Truls Aagedal
// SPDX-License-Identifier: GPL-3.0-or-later

import SwiftUI

struct MetadataSettingsView: View {
    @AppStorage(AppConstants.includeDateTagPreferenceKey) private var includeDateTagByDefault = false
    @AppStorage(AppConstants.preserveMetadataPreferenceKey) private var preserveMetadataByDefault = false
    @AppStorage(AppConstants.defaultTimecodeModeKey) private var defaultTimecodeModeRaw = AppConstants.defaultTimecodeModeRaw
    @AppStorage(AppConstants.defaultTimecodeValueKey) private var defaultTimecodeValue = AppConstants.defaultTimecodeValue

    @State private var isValidTimecode: Bool = true
    @FocusState private var isTextFieldFocused: Bool

    private enum TimecodeDefaultMode: String, CaseIterable, Identifiable {
        case preserveSource = "preserveSource"
        case manual = "manual"
        case disabled = "disabled"

        var id: String { rawValue }

        var displayName: String {
            switch self {
            case .preserveSource: return "Preserve Source"
            case .manual: return "Manual Override"
            case .disabled: return "Disable"
            }
        }
    }

    private var selectedMode: TimecodeDefaultMode {
        TimecodeDefaultMode(rawValue: defaultTimecodeModeRaw) ?? .preserveSource
    }

    var body: some View {
        Form {
            metadataPreservationSection
            timecodeDefaultsSection
        }
        .formStyle(.grouped)
        .onAppear {
            isValidTimecode = validateTimecode(defaultTimecodeValue)
        }
    }

    private var metadataPreservationSection: some View {
        Section(header: Text("Metadata Preservation")) {
            VStack(alignment: .leading, spacing: 8) {
                Toggle("Preserve all original metadata", isOn: $preserveMetadataByDefault)
                    .toggleStyle(SwitchToggleStyle())
                    .help("When enabled, the original file's metadata is kept intact during conversion")
                Text("By default, metadata such as title, timecode, and encoder tags are stripped to keep output files clean. Enable this to keep all metadata untouched. However, color related metadata (including HDR) will always be preserved, to assure an accurate viewing experience.")
                    .font(Font.caption.italic())
                    .foregroundColor(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
            }
            .padding(8)

            VStack(alignment: .leading, spacing: 8) {
                Toggle(isOn: $includeDateTagByDefault) {
                    VStack(alignment: .leading, spacing: 4) {
                        Label("Include date tag on new files", systemImage: "calendar.badge.clock")
                            .font(.subheadline.weight(.semibold))
                        Text("Date tag is an autogenerated text added to the beginning of the comment field, e.g. 'Date generated: 20250925'. The tag precedes any custom comment you enter on the video card.")
                            .font(Font.caption.italic())
                            .foregroundColor(preserveMetadataByDefault ? .secondary : .primary)
                            .fixedSize(horizontal: false, vertical: true)
                    }
                }
                .toggleStyle(SwitchToggleStyle())
                .disabled(preserveMetadataByDefault)
                .help("Controls whether newly added files include the \"Date generated\" metadata tag by default")
            }
            .padding(8)
        }
    }

    private var timecodeDefaultsSection: some View {
        Section(header: Text("Timecode Defaults")) {
            VStack(alignment: .leading, spacing: 12) {
                Text("Default timecode mode for new files:")
                    .font(.headline)

                Picker("Default Mode", selection: $defaultTimecodeModeRaw) {
                    ForEach(TimecodeDefaultMode.allCases) { mode in
                        Text(mode.displayName).tag(mode.rawValue)
                    }
                }
                .pickerStyle(.segmented)

                switch selectedMode {
                case .preserveSource:
                    HStack {
                        Image(systemName: "info.circle")
                            .foregroundColor(.blue)
                        Text("The timecode from the source file will be copied to the output.")
                            .font(.caption)
                            .foregroundColor(.secondary)
                            .fixedSize(horizontal: false, vertical: true)
                    }
                    .padding(.top, 4)

                case .manual:
                    VStack(alignment: .leading, spacing: 8) {
                        HStack {
                            Image(systemName: "info.circle")
                                .foregroundColor(.blue)
                            Text("Enter a default start timecode for output files.")
                                .font(.caption)
                                .foregroundColor(.secondary)
                                .fixedSize(horizontal: false, vertical: true)
                        }

                        VStack(alignment: .leading, spacing: 6) {
                            Text("Default Timecode Value:")
                                .font(.subheadline.weight(.semibold))

                            HStack(spacing: 6) {
                                // Subtract buttons
                                Button(action: { adjustFrames(by: -10) }) {
                                    Text("-10")
                                        .font(.caption)
                                        .frame(minWidth: 32)
                                }
                                .buttonStyle(.bordered)
                                .controlSize(.small)
                                .help("Subtract 10 frames")

                                Button(action: { adjustFrames(by: -1) }) {
                                    Text("-1")
                                        .font(.caption)
                                        .frame(minWidth: 32)
                                }
                                .buttonStyle(.bordered)
                                .controlSize(.small)
                                .help("Subtract 1 frame")

                                // Timecode input field
                                TextField("00:00:00:00", text: $defaultTimecodeValue)
                                    .textFieldStyle(.roundedBorder)
                                    .font(.system(.body, design: .monospaced))
                                    .focused($isTextFieldFocused)
                                    .onChange(of: defaultTimecodeValue) { _, newValue in
                                        let sanitized = sanitizeTimecode(newValue)
                                        if sanitized != newValue {
                                            defaultTimecodeValue = sanitized
                                        }
                                        isValidTimecode = validateTimecode(sanitized)
                                    }
                                    .onChange(of: isTextFieldFocused) { _, isFocused in
                                        // Auto-correct when losing focus
                                        if !isFocused {
                                            autoCorrectTimecode()
                                        }
                                    }
                                    .onSubmit {
                                        autoCorrectTimecode()
                                    }

                                // Add buttons
                                Button(action: { adjustFrames(by: 1) }) {
                                    Text("+1")
                                        .font(.caption)
                                        .frame(minWidth: 32)
                                }
                                .buttonStyle(.bordered)
                                .controlSize(.small)
                                .help("Add 1 frame")

                                Button(action: { adjustFrames(by: 10) }) {
                                    Text("+10")
                                        .font(.caption)
                                        .frame(minWidth: 32)
                                }
                                .buttonStyle(.bordered)
                                .controlSize(.small)
                                .help("Add 10 frames")
                            }

                            if !isValidTimecode {
                                HStack {
                                    Image(systemName: "exclamationmark.triangle.fill")
                                        .foregroundColor(.orange)
                                        .font(.caption)
                                    Text(validationErrorMessage())
                                        .font(.caption)
                                        .foregroundColor(.orange)
                                }
                            } else {
                                Text("Format: HH:MM:SS:FF (hours: 00-23, frames: 00-29 for 30fps) or HH:MM:SS;FF for drop-frame")
                                    .font(.caption)
                                    .foregroundColor(.secondary)
                                    .fixedSize(horizontal: false, vertical: true)
                            }
                        }
                    }
                    .padding(.top, 4)

                case .disabled:
                    HStack {
                        Image(systemName: "info.circle")
                            .foregroundColor(.blue)
                        Text("No timecode will be written to output files by default.")
                            .font(.caption)
                            .foregroundColor(.secondary)
                            .fixedSize(horizontal: false, vertical: true)
                    }
                    .padding(.top, 4)
                }
            }
            .padding(8)
        }
    }

    // MARK: - Timecode Validation & Sanitization

    private func sanitizeTimecode(_ input: String) -> String {
        // Only allow digits, colons, and semicolons
        let allowed = CharacterSet(charactersIn: "0123456789:;")
        let filtered = input.filter { char in
            char.unicodeScalars.allSatisfy { allowed.contains($0) }
        }

        // Limit length to 11 characters (HH:MM:SS:FF or HH:MM:SS;FF)
        let truncated = String(filtered.prefix(11))

        return truncated
    }

    private func validateTimecode(_ input: String) -> Bool {
        // Valid formats: HH:MM:SS:FF or HH:MM:SS;FF
        let pattern = "^\\d{2}:\\d{2}:\\d{2}[:;]\\d{2}$"

        guard let regex = try? NSRegularExpression(pattern: pattern) else {
            return false
        }

        let range = NSRange(location: 0, length: input.utf16.count)
        let matches = regex.firstMatch(in: input, range: range)

        if matches == nil {
            return false
        }

        // Additional validation: hours, minutes, seconds, frames should be in valid ranges
        let components = input.split(whereSeparator: { $0 == ":" || $0 == ";" })
        guard components.count == 4,
              let hours = Int(components[0]),
              let minutes = Int(components[1]),
              let seconds = Int(components[2]),
              let frames = Int(components[3]) else {
            return false
        }

        // Hours: 0-23 (24-hour format)
        guard hours < 24 else { return false }

        // Minutes: 0-59
        guard minutes < 60 else { return false }

        // Seconds: 0-59
        guard seconds < 60 else { return false }

        // Frames: 0-29 (default to 30fps for settings)
        guard frames < 30 else { return false }

        return true
    }

    private func validationErrorMessage() -> String {
        let components = defaultTimecodeValue.split(whereSeparator: { $0 == ":" || $0 == ";" })

        if components.count != 4 {
            return "Invalid format. Use HH:MM:SS:FF or HH:MM:SS;FF"
        }

        guard let hours = Int(components[0]),
              let minutes = Int(components[1]),
              let seconds = Int(components[2]),
              let frames = Int(components[3]) else {
            return "Invalid format. Use HH:MM:SS:FF or HH:MM:SS;FF"
        }

        if hours >= 24 {
            return "Hours must be 00-23"
        }

        if minutes >= 60 {
            return "Minutes must be 00-59"
        }

        if seconds >= 60 {
            return "Seconds must be 00-59"
        }

        if frames >= 30 {
            return "Frames must be 00-29 (30fps default)"
        }

        return "Invalid timecode format"
    }

    private func autoCorrectTimecode() {
        let components = defaultTimecodeValue.split(whereSeparator: { $0 == ":" || $0 == ";" })

        // If format is completely wrong, reset to default
        guard components.count == 4 else {
            defaultTimecodeValue = "00:00:00:00"
            isValidTimecode = true
            return
        }

        // Parse components
        guard let hours = Int(components[0]),
              let minutes = Int(components[1]),
              let seconds = Int(components[2]),
              let frames = Int(components[3]) else {
            defaultTimecodeValue = "00:00:00:00"
            isValidTimecode = true
            return
        }

        // Clamp each component to valid range
        let clampedHours = min(hours, 23)
        let clampedMinutes = min(minutes, 59)
        let clampedSeconds = min(seconds, 59)
        let clampedFrames = min(frames, 29) // Default to 30fps

        // Preserve the separator (: or ;)
        let separator = defaultTimecodeValue.contains(";") ? ";" : ":"

        // Build corrected timecode
        let corrected = String(format: "%02d:%02d:%02d%@%02d",
                              clampedHours,
                              clampedMinutes,
                              clampedSeconds,
                              separator,
                              clampedFrames)

        defaultTimecodeValue = corrected
        isValidTimecode = true
    }

    private func adjustFrames(by delta: Int) {
        let components = defaultTimecodeValue.split(whereSeparator: { $0 == ":" || $0 == ";" })

        guard components.count == 4,
              let hours = Int(components[0]),
              let minutes = Int(components[1]),
              let seconds = Int(components[2]),
              let frames = Int(components[3]) else {
            return
        }

        let maxFrames = 30 // Default to 30fps

        // Convert everything to total frames
        var totalFrames = hours * 3600 * maxFrames
        totalFrames += minutes * 60 * maxFrames
        totalFrames += seconds * maxFrames
        totalFrames += frames

        // Add delta
        totalFrames += delta

        // Ensure non-negative
        totalFrames = max(0, totalFrames)

        // Convert back to timecode components
        var newFrames = totalFrames % maxFrames
        totalFrames /= maxFrames

        var newSeconds = totalFrames % 60
        totalFrames /= 60

        var newMinutes = totalFrames % 60
        totalFrames /= 60

        var newHours = totalFrames % 24

        // Clamp to 23:59:59:FF
        if newHours >= 24 {
            newHours = 23
            newMinutes = 59
            newSeconds = 59
            newFrames = maxFrames - 1
        }

        // Preserve the separator (: or ;)
        let separator = defaultTimecodeValue.contains(";") ? ";" : ":"

        // Build new timecode
        defaultTimecodeValue = String(format: "%02d:%02d:%02d%@%02d",
                                newHours,
                                newMinutes,
                                newSeconds,
                                separator,
                                newFrames)

        isValidTimecode = true
    }
}

#Preview {
    MetadataSettingsView()
}
